const INITIAL_QUOTES = [
  // ── 偉人・歴史上の人物 ────────────────────────────────────
  { id: 1, text: "不可能とは、小さな人間の言葉だ。", author: "ナポレオン・ボナパルト", category: "historical" },
  { id: 2, text: "失敗した時に諦めることが、最大の失敗だ。", author: "エイブラハム・リンカーン", category: "historical" },
  { id: 3, text: "私は一万通りの失敗した方法を発見しただけだ。それは失敗ではなく、成功への道だ。", author: "トーマス・エジソン", category: "historical" },
  { id: 4, text: "人生は大胆な冒険か、何もないかのどちらかだ。", author: "ヘレン・ケラー", category: "historical" },
  { id: 5, text: "あなた自身が見たいと思う変化に、あなた自身がなりなさい。", author: "マハトマ・ガンジー", category: "historical" },
  { id: 6, text: "人生は恐れるものではなく、理解するものだ。", author: "マリー・キュリー", category: "historical" },
  { id: 7, text: "学ぶことに飽きた者は、もう老いている。", author: "レオナルド・ダ・ヴィンチ", category: "historical" },
  { id: 8, text: "想像力は知識よりも大切だ。知識には限りがあるが、想像力は世界を包む。", author: "アルベルト・アインシュタイン", category: "historical" },
  { id: 9, text: "成功とは、失敗を重ねても情熱を失わないことだ。", author: "ウィンストン・チャーチル", category: "historical" },
  { id: 10, text: "世の人は我を何とも言わば言え、我なす事は我のみぞ知る。", author: "坂本龍馬", category: "historical" },
  { id: 11, text: "不自由を常と思えば不足なし。心に望み起らば、困窮した時を思い出すべし。", author: "徳川家康", category: "historical" },
  { id: 12, text: "昨日は過ぎ去りました。明日はまだ来ていません。今日しかないのです。", author: "マザー・テレサ", category: "historical" },
  { id: 13, text: "今日できることを明日に延ばすな。", author: "ベンジャミン・フランクリン", category: "historical" },
  { id: 14, text: "生き残るのは最も強い者でも最も賢い者でもない。変化に最もよく適応した者だ。", author: "チャールズ・ダーウィン", category: "historical" },
  { id: 15, text: "人間はすべて天才だ。しかし、木登りの能力で魚を判断すれば、魚は一生、自分はダメだと思い込む。", author: "アルベルト・アインシュタイン", category: "historical" },
  { id: 16, text: "あなたが失敗するのを恐れているなら、あなたはすでに失敗している。", author: "フレデリック・フォーサイス", category: "historical" },
  { id: 17, text: "信じる力が奇跡を起こす。", author: "マザー・テレサ", category: "historical" },
  { id: 18, text: "人の価値は、何を得るかではなく、何を与えるかで決まる。", author: "アルベルト・アインシュタイン", category: "historical" },
  { id: 19, text: "偉大な業績は、すべて小さな一歩から始まる。", author: "レオナルド・ダ・ヴィンチ", category: "historical" },
  { id: 20, text: "我々は皆、星のかけらでできている。", author: "カール・セーガン", category: "historical" },
  { id: 21, text: "行動なき夢想は白昼夢。夢想なき行動は悪夢だ。", author: "T・E・ロレンス", category: "historical" },
  { id: 22, text: "民主主義とは、最悪の政治形態だ。これまで試みられてきた他のすべてを除けば。", author: "ウィンストン・チャーチル", category: "historical" },
  { id: 23, text: "知ることは好むことに及ばず、好むことは楽しむことに及ばない。", author: "孔子", category: "historical" },
  { id: 24, text: "千里の道も一歩から。", author: "老子", category: "historical" },
  { id: 25, text: "人生は短い。愚かに過ごす暇などない。", author: "ヴィクトル・ユーゴー", category: "historical" },

  // ── 哲学・思想家 ────────────────────────────────────────
  { id: 26, text: "無知の知こそが知恵の始まりだ。", author: "ソクラテス", category: "philosophy" },
  { id: 27, text: "我思う、ゆえに我あり。", author: "ルネ・デカルト", category: "philosophy" },
  { id: 28, text: "怪物と戦う者は、自らも怪物にならないように注意せよ。", author: "フリードリヒ・ニーチェ", category: "philosophy" },
  { id: 29, text: "神は死んだ。我々が神を殺したのだ。", author: "フリードリヒ・ニーチェ", category: "philosophy" },
  { id: 30, text: "人を手段としてではなく、常に目的として扱え。", author: "イマヌエル・カント", category: "philosophy" },
  { id: 31, text: "人間は考える葦だ。", author: "ブレーズ・パスカル", category: "philosophy" },
  { id: 32, text: "実存は本質に先立つ。", author: "ジャン＝ポール・サルトル", category: "philosophy" },
  { id: 33, text: "愛するということは、一緒に同じ方向を見つめることだ。", author: "アントワーヌ・ド・サン＝テグジュペリ", category: "philosophy" },
  { id: 34, text: "人は自由に生まれながら、いたるところで鎖につながれている。", author: "ジャン＝ジャック・ルソー", category: "philosophy" },
  { id: 35, text: "全ての優れたものは、稀であると同時に困難だ。", author: "バルーフ・デ・スピノザ", category: "philosophy" },
  { id: 36, text: "才能は射手が他の人には難しい的を射ることだ。天才は他の人には見えない的を射ることだ。", author: "アルトゥル・ショーペンハウアー", category: "philosophy" },
  { id: 37, text: "語り得ぬものについては、沈黙しなければならない。", author: "ルートヴィヒ・ウィトゲンシュタイン", category: "philosophy" },
  { id: 38, text: "我々の最大の栄光は、一度も失敗しないことではなく、倒れるたびに起き上がることにある。", author: "オリバー・ゴールドスミス", category: "philosophy" },
  { id: 39, text: "幸福とは、夢を追いかける旅の途中にある。", author: "エリック・バターワース", category: "philosophy" },
  { id: 40, text: "知識の土台は、知らないということを知ることだ。", author: "ソクラテス", category: "philosophy" },
  { id: 41, text: "美しいものは困難だ。", author: "プラトン", category: "philosophy" },
  { id: 42, text: "我々は繰り返すことで、そういう人間になる。だから卓越性は行為ではなく習慣だ。", author: "アリストテレス", category: "philosophy" },
  { id: 43, text: "時間とは川のようなもの。同じ川に二度入ることはできない。", author: "ヘラクレイトス", category: "philosophy" },
  { id: 44, text: "幸福とは探すものではなく、創り出すものだ。", author: "バートランド・ラッセル", category: "philosophy" },
  { id: 45, text: "現在だけが本当に存在する。過去と未来は心の中にしかない。", author: "ゴータマ・ブッダ", category: "philosophy" },
  { id: 46, text: "疑うことから哲学は始まる。", author: "アリストテレス", category: "philosophy" },
  { id: 47, text: "正しく生きることは、幸せに生きることだ。", author: "プラトン", category: "philosophy" },
  { id: 48, text: "運命を愛せよ。それがどれほど過酷であっても。", author: "フリードリヒ・ニーチェ", category: "philosophy" },
  { id: 49, text: "自分を知ることが、あらゆる知恵の始まりだ。", author: "アリストテレス", category: "philosophy" },
  { id: 50, text: "哲学とは死を学ぶことだ。", author: "ミシェル・ド・モンテーニュ", category: "philosophy" },

  // ── ビジネス・成功者 ────────────────────────────────────
  { id: 51, text: "偉大な仕事をする唯一の方法は、やっていることを好きになることだ。", author: "スティーブ・ジョブズ", category: "business" },
  { id: 52, text: "成功を祝うのはいいが、もっと重要なのは失敗から学ぶことだ。", author: "ビル・ゲイツ", category: "business" },
  { id: 53, text: "失敗の原因を素直に認識し、それを次の出発点とできるならば、失敗は成功のもとになる。", author: "松下幸之助", category: "business" },
  { id: 54, text: "私の最大の光栄は、一度も失敗しないことではなく、倒れるたびに起き上がることにある。", author: "本田宗一郎", category: "business" },
  { id: 55, text: "人生は今この瞬間の連続である。今を懸命に生きることが、素晴らしい未来を作る。", author: "稲盛和夫", category: "business" },
  { id: 56, text: "最大のリスクは、リスクを取らないことだ。変化の速い世界では、確実に失敗する戦略だ。", author: "マーク・ザッカーバーグ", category: "business" },
  { id: 57, text: "失敗は選択肢の一つだ。失敗しないということは、革新していないということだ。", author: "イーロン・マスク", category: "business" },
  { id: 58, text: "予測するための最良の方法は、それを創ることだ。", author: "ピーター・ドラッカー", category: "business" },
  { id: 59, text: "他の人が貪欲なときに恐れ、他の人が恐れているときに貪欲になれ。", author: "ウォーレン・バフェット", category: "business" },
  { id: 60, text: "変化する前に変化せよ。そうしなければ、変化させられる。", author: "ジャック・ウェルチ", category: "business" },
  { id: 61, text: "リーダーシップとは、人々の可能性を信じ、その可能性を引き出すことだ。", author: "リー・アイアコッカ", category: "business" },
  { id: 62, text: "志高くあれ。人生の大半の出来事は志によって決まる。", author: "孫正義", category: "business" },
  { id: 63, text: "失敗とは諦めることだ。成功するまでやり続ければ、失敗にならない。", author: "柳井正", category: "business" },
  { id: 64, text: "楽観的に発想し、悲観的に計画して、楽観的に実行する。", author: "三木谷浩史", category: "business" },
  { id: 65, text: "もし私が人々に何が欲しいかを聞いたとしたら、もっと速い馬と言っただろう。", author: "ヘンリー・フォード", category: "business" },
  { id: 66, text: "もしチャンスが来たら、とにかく飛び乗れ。後で詳細を決めればいい。", author: "リチャード・ブランソン", category: "business" },
  { id: 67, text: "顧客は常に正しい。ただし、顧客が間違っている場合を除いて。", author: "ゴードン・ラムゼイ", category: "business" },
  { id: 68, text: "アイデアに価値はない。実行にのみ価値がある。", author: "トーマス・エジソン", category: "business" },
  { id: 69, text: "素晴らしいものを作れば、人は必ずやってくる。", author: "スティーブ・ジョブズ", category: "business" },
  { id: 70, text: "才能は武器だ。しかし、努力は才能を超える。", author: "松下幸之助", category: "business" },
  { id: 71, text: "一番危険な思い込みは、自分はもう十分に学んだというものだ。", author: "ピーター・ドラッカー", category: "business" },
  { id: 72, text: "顧客を喜ばせることに全力を尽くせ。利益はその結果としてついてくる。", author: "稲盛和夫", category: "business" },
  { id: 73, text: "自分よりも優秀な人を集める技術こそが、成功の秘訣だ。", author: "アンドリュー・カーネギー", category: "business" },
  { id: 74, text: "できない理由を探すより、できる方法を探せ。", author: "マイケル・デル", category: "business" },
  { id: 75, text: "人材こそが最大の資産だ。機械は人を置き換えても、人の創造性は置き換えられない。", author: "本田宗一郎", category: "business" },

  // ── スポーツ選手 ────────────────────────────────────────
  { id: 76, text: "失敗できると気づいた時、それが成功の始まりだ。", author: "マイケル・ジョーダン", category: "sports" },
  { id: 77, text: "不可能とは、自らの力で世界を変えようとしない弱い者の言葉だ。", author: "モハメド・アリ", category: "sports" },
  { id: 78, text: "小さなことを積み重ねることが、とんでもないところへ行くただ一つの道。", author: "イチロー", category: "sports" },
  { id: 79, text: "自分の可能性を信じて、諦めないことが大切だ。", author: "大谷翔平", category: "sports" },
  { id: 80, text: "ピッチの外で何をするかが、ピッチの中でどうプレーするかを決める。", author: "本田圭佑", category: "sports" },
  { id: 81, text: "努力は裏切らない。それが私の信念だ。", author: "ロジャー・フェデラー", category: "sports" },
  { id: 82, text: "チャンピオンは諦めない人だ。負けたとき、諦めさえしなければ負けではない。", author: "ラファエル・ナダル", category: "sports" },
  { id: 83, text: "努力なくして夢の実現はない。一秒一秒を大切に生きろ。", author: "ウサイン・ボルト", category: "sports" },
  { id: 84, text: "限界は自分が作るものだ。諦めない限り可能性は無限だ。", author: "シモーネ・バイルス", category: "sports" },
  { id: 85, text: "才能は努力なしには意味がない。努力こそが才能を引き出す鍵だ。", author: "クリスティアーノ・ロナウド", category: "sports" },
  { id: 86, text: "夢を持つことをやめたら、人生は終わる。", author: "リオネル・メッシ", category: "sports" },
  { id: 87, text: "ゲームを変えるのは才能ではなく、努力と献身だ。", author: "ルブロン・ジェームズ", category: "sports" },
  { id: 88, text: "朝4時のロサンゼルスを知っているか？私は知っている。毎日そこで練習していた。", author: "コービー・ブライアント", category: "sports" },
  { id: 89, text: "逃げない、はればれと立ち向かう、それがぼくのモットーです。", author: "松井秀喜", category: "sports" },
  { id: 90, text: "一流は人に優しく自分に厳しい。二流は人に厳しく自分に甘い。", author: "野村克也", category: "sports" },
  { id: 91, text: "自分を信じてその可能性を信じて進んでいくことが、一番大切なことだと思う。", author: "羽生結弦", category: "sports" },
  { id: 92, text: "勝つためには、負けを恐れてはいけない。", author: "タイガー・ウッズ", category: "sports" },
  { id: 93, text: "成功とは、できる限りの自分になるための準備をすることだ。", author: "ジョン・ウッデン", category: "sports" },
  { id: 94, text: "意志は習慣となり、習慣は性格となり、性格は運命となる。", author: "ビンス・ロンバルディ", category: "sports" },
  { id: 95, text: "痛みは一時的だ。諦めは永遠に続く。", author: "ランス・アームストロング", category: "sports" },
  { id: 96, text: "毎日少しずつでも前に進めば、いつかは遠くまで来られる。", author: "イチロー", category: "sports" },
  { id: 97, text: "私が最も怖れるのは、自分自身の限界だ。", author: "大坂なおみ", category: "sports" },
  { id: 98, text: "チームメイトを信じること。それが最強のパワーだ。", author: "澤穂希", category: "sports" },
  { id: 99, text: "練習は嘘をつかない。ただし、正しい練習に限る。", author: "野村克也", category: "sports" },
  { id: 100, text: "勝利よりも、勝利への過程に意味がある。", author: "ロジャー・フェデラー", category: "sports" }
];

const CATEGORY_LABELS = {
  historical: "偉人・歴史",
  philosophy: "哲学・思想",
  business: "ビジネス",
  sports: "スポーツ"
};
